<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Doctrine\Query\Queries;
use Eccube\Entity\ProductClass;
use Eccube\Util\StringUtil;

/**
 * ProductClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductClassRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    public function __construct(
        RegistryInterface $registry,
        Queries           $queries
    )
    {
        parent::__construct($registry, ProductClass::class);
        $this->queries = $queries;
    }

    /**
     * Increment stock of products
     *
     * @param ProductClass $entity
     * @param int stock
     * @return int|mixed|string
     */
    public function incrementStock(ProductClass $entity, $stock = 0)
    {
        return $this
            ->createQueryBuilder('pc')
            ->update()
            ->set('pc.stock', 'case when pc.stock is null then ' . $stock . ' else pc.stock + 1 end')
            ->where('pc.id = :id')
            ->setParameter('id', $entity->getId())
            ->getQuery()
            ->execute();
    }

    /**
     * Decrement stock of products
     * 
     * @param ProductClass $entity
     * @param int stock
     * @return int|mixed|string
     */
    public function decrementStock(ProductClass $entity, $stock = 0)
    {
        return $this
            ->createQueryBuilder('pc')
            ->update()
            ->set('pc.stock', 'case when pc.stock > 0 then pc.stock - ' . $stock . 'else 0 end')
            ->where('pc.id = :id')
            ->setParameter('id', $entity->getId())
            ->getQuery()
            ->execute();
    }

    /**
     * get query builder.
     *
     * @param array $searchData
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderBySearchDataForAdmin($searchData)
    {
        $qb = $this->createQueryBuilder('pc')
            ->addSelect('p')
            ->innerJoin('pc.Product', 'p')
            ->andWhere('pc.visible = :visible')
            ->setParameter('visible', true);

        if (isset($searchData['keyword']) && StringUtil::isNotBlank($searchData['keyword'])) {
            $qb
                ->andWhere('p.name LIKE :likekeyword OR pc.code LIKE :likekeyword')
                ->setParameter('likekeyword', '%' . str_replace(['%', '_'], ['\\%', '\\_'], $searchData['keyword']) . '%');
        }
        $qb
            ->orderBy('pc.update_date', 'DESC');
        return $this->queries->customize(QueryKey::PRODUCT_SEARCH_ADMIN, $qb, $searchData);
    }
}
