<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Eccube\Entity\ProductClass;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ProductClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductClassRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ProductClass::class);
    }

    /**
     * Increment stock of products
     *
     * @param ProductClass $entity
     * @return int|mixed|string
     */
    public function incrementCount(ProductClass $entity, $stock = 0)
    {
        return $this
            ->createQueryBuilder('pc')
            ->update()
            ->set('pc.stock', 'case when pc.stock is null then ' . $stock . ' else pc.stock + 1 end')
            ->where('pc.id = :id')
            ->setParameter('id', $entity->getId())
            ->getQuery()
            ->execute();
    }

    /**
     * Decrement favorite count of pet
     *
     * @param ProductClass $entity
     * @return int|mixed|string
     */
    public function decrementCount(ProductClass $entity, $stock = 0)
    {
        return $this
            ->createQueryBuilder('pc')
            ->update()
            ->set('pc.stock', 'case when pc.stock > 0 then pc.stock - ' . $stock . 'else 0 end')
            ->where('pc.id = :id')
            ->setParameter('id', $entity->getId())
            ->getQuery()
            ->execute();
    }
}
