<?php

namespace Plugin\ZooopsSubscription\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ZooopsSubscription\Entity\SubscriptionContract;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\QueryBuilder;
use Eccube\Doctrine\Query\Queries;
use Eccube\Repository\QueryKey;

/**
 * SubscriptionContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionContractRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * SubscriptionContractRepository constructor.
     *
     * @param ManagerRegistry $registry
     * @param Queries $queries
     */
    public function __construct(ManagerRegistry $registry, Queries $queries)
    {
        parent::__construct($registry, SubscriptionContract::class);
        $this->queries = $queries;
    }

    /**
     * 検索処理
     *
     * @param  array $searchData
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getSearchData($searchData)
    {
        $qb = $this->createQueryBuilder('pzsc')
            ->where('pzsc.contract_date IS NOT NULL')
            ->addOrderBy('pzsc.id', 'ASC')
            ->innerJoin('Eccube\Entity\Customer', 'c', 'WITH', 'pzsc.Customer = c.id');

        // 注文者名検索
        if (!empty($searchData['customer_name']) && $searchData['customer_name']) {
            $qb
                ->andWhere('CONCAT(c.name01, c.name02)  LIKE :customer_name')
                ->setParameter('customer_name',  '%' . $searchData['customer_name'] . '%');
        }

        // 次回配送日検索
        // 次回配送日(開始)
        if (!empty($searchData['next_delivery_date_start']) && $searchData['next_delivery_date_start']) {
            $date = $searchData['next_delivery_date_start'];
            $qb
                ->andWhere('pzsc.next_delivery_date >= :next_delivery_date_start')
                ->setParameter('next_delivery_date_start', $date);
        }

        // 次回配送日(終了)
        if (!empty($searchData['next_delivery_date_end']) && $searchData['next_delivery_date_end']) {
            $date = clone $searchData['next_delivery_date_end'];
            $qb
                ->andWhere('pzsc.next_delivery_date <= :next_delivery_date_end')
                ->setParameter('next_delivery_date_end', $date);
        }

        $searchResult = $qb
            ->getQuery()
            ->getResult();

        // 検索結果を返す
        return $searchResult;
    }

    /**
     * @param  \Eccube\Entity\Customer $Customer
     *
     * @return QueryBuilder
     */
    public function getQueryBuilderByCustomer(\Eccube\Entity\Customer $Customer)
    {
        $qb = $this->createQueryBuilder('s')
            ->where('s.Customer = :Customer')
            ->setParameter('Customer', $Customer)
            ->andwhere('s.contract_date IS NOT NULL');

        // Order By
        $qb->addOrderBy('s.id', 'DESC');

        return $this->queries->customize('SubscriptionContract.getQueryBuilderByCustomer', $qb, ['customer' => $Customer]);
    }
}
