<?php

/*
 * Copyright(c) 2018 GMO Payment Gateway, Inc. All rights reserved.
 * http://www.gmo-pg.com/
 */

namespace Plugin\GmoPaymentGateway4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\GmoPaymentGateway4\Entity\GmoConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\HttpKernel\KernelInterface;

/**
 * GmoConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GmoConfigRepository extends AbstractRepository
{
    /**
     * GmoConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, GmoConfig::class);
    }

    /**
     * @param int $id
     * @return null|GmoConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
