<?php

namespace Customize\Repository;

use Customize\Entity\BusinessHoliday;
use DateTime;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Eccube\Repository\AbstractRepository;

/**
 * BusinessHolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessHolidayRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, BusinessHoliday::class);
    }

    /**
     * Get future holidays.
     *
     * @param $year
     * @return array
     */
    public function getFutureHolidays($year): array
    {
        return $this->createQueryBuilder('h')
            ->where('h.holiday_date >= :fromDate')
            ->andWhere('h.holiday_date <= :toDate')
            ->setParameters(['fromDate' => $year . '/01/01', 'toDate' => $year . '/12/31'])
            ->orderBy('h.holiday_date', 'DESC')
            ->getQuery()
            ->getResult();
    }
}