<?php

namespace Customize\Repository;

use Customize\Entity\BusinessHoliday;
use DateTime;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Eccube\Repository\AbstractRepository;

/**
 * BusinessHolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessHolidayRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, BusinessHoliday::class);
    }

    /**
     * Get future holidays.
     *
     * @param ?DateTime $fromDateTime
     * @return array
     */
    public function getFutureHolidays(?DateTime $fromDateTime = null): array
    {
        return $this->createQueryBuilder('h')
            ->andWhere('h.holiday_date > :from_datetime')
            ->setParameters(['from_datetime' => ($fromDateTime ?? new DateTime)->format('Y-m-d')])
            ->orderBy('h.holiday_date', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
