<?php
namespace Customize\Repository;

use Customize\Entity\ScheduledMail;
use Doctrine\Persistence\ManagerRegistry;
use Eccube\Repository\AbstractRepository;

/**
 * ScheduledMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduledMailRepository extends AbstractRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ScheduledMail::class);
    }
}
