<?php

namespace Plugin\ZooopsSendmail\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ZooopsSendmail\Entity\MailTemplate;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTemplateRepository extends AbstractRepository
{
    /**
     * MailTemplateRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, MailTemplate::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
